### PR TITLE
wip: move long lived jobs for doks to orbs

### PR DESCRIPTION
**Pull request by joaocosta-codacy**
The orbs for the workflows that we will use in the self-hosted enterprise digital ocean.

### CODE REVIEW

**Comment by andreaTP** [comment]
Why don't we do a specific orb for docs? Especially thinking about the fact that this is going to be disposed in a few months.

**Comment by joaocosta-codacy** [comment]
I am not sure I follow. All the orbs (jobs and executor) that were created are specific to doks. Later on, we might make them independent from a given cloud provider.

**Comment by andreaTP** [comment]
What I mean is, we can create and publish a separate orb just for docs.
Given the fact that this is not a technology that we are planning to use long-term I don't see a strong motivation into merging these into `codacy/base`.
Other opinions are appreciated on the topic cc. @rtfpessoa @paulopontesm

**Comment by joaocosta-codacy** [comment]
We have decided that instead of using orbs to use references (yaml anchors) since this is going to be aimed at doks only. Dropping PR.

**Pull request closed without merging**
