### PR TITLE
fix: Adjust cache name to force a reset on circle

### PR DESCRIPTION
**Pull request by peavers**

### CODE REVIEW

**Comment by machadoit** [comment]
Maybe I don't have enough context, and this change seems fine for now. But for me, seems really strange that the orb has this cache thingy. Because we use this orb multiple times on the same build, what happens if you override the cache in some places, and forget on others?

I will take the question to a different scope, and it is not the aim of this PR

**Comment by paulopontesm** [comment]
I think @andreaTP can have some input on how he thought the usage of this var.

**Comment by andreaTP** [comment]
@machadoit the fact that the setting is in the orb is to give a default to keep backward compatibility.

**Comment by peavers** [comment]
Since this is no longer directly blocking us; I'm going to go ahead and close this.

**Pull request closed without merging**
